require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - bin/*
    - vendor/bundle/**/*
Style/Documentation:
  Enabled: false
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition