name: Verify
on: [push]

jobs:
  default:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:setup
      - name: Run linters
        run: |
          bin/bundle exec rubocop
      - name: Run security checks
        run: |
          bin/bundle exec brakeman -q -w2
      - name: Run tests
        run: |
          bin/rails test
          cat coverage/lcov.info
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
