name: Verify
on: [push]

jobs:
  default:
    name: Default
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install npm dependencies
        run: |
          yarn install
      - name: Setup test database
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:setup
      - name: Run linters
        run: |
          bin/bundle exec rubocop
          yarn lint
      - name: Run security checks
        run: |
          bin/bundle exec brakeman -q -w2
      - name: Run build
        run: |
          yarn build
          bin/rails assets:precompile
      - name: Run tests
        run: |
          bin/rails test
          mv coverage/lcov.info coverage/backend.lcov.info
          yarn test:coverage
          mv coverage/lcov.info coverage/frontend.lcov.info
          ./node_modules/.bin/lcov-result-merger 'coverage/*.lcov.info' 'coverage/lcov.info'
      - name: Coveralls frontend
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      
